<?php if ($this->pageCount): ?>
<?php 
    $query = [];

    if ($params['sort'] != -1) $query['sort'] = $params['sort']; 
    if ($params['color'] != -1) $query['color'] = $params['color'];
    if ($params['sort'] != -1) $query['sort'] = $params['sort'];
    if ($params['price_gte'] != -1) $query['price_gte'] = $params['price_gte'];
    if ($params['price_lte'] != -1) $query['price_lte'] = $params['price_lte'];
?>
<nav>
<ul class="pagination">

<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
    <?php $query['page'] = $this->previous;?>
    <li>
      <a href="<?= $this->url($this->route, ['action' => $this->action,'id' => $this->id], 
                              ['query' => $query]); ?>" 
        aria-label="Previous">       
        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>  
<?php else: ?>
    <li>
        <span aria-hidden="true">&laquo;</span>      
    </li>  
<?php endif; ?>

<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?>
  <?php if ($page != $this->current): ?>
    <?php $query['page'] = $page;?>
    <li>
        <a href="<?= $this->url($this->route, ['action' => $this->action,'id' => $this->id], 
                                ['query' => $query]); ?>">
            <?= $this->escapeHtml($page); ?>      
        </a>
    </li>    
  <?php else: ?>
    <li>
        <span aria-hidden="true"><b><?= $this->escapeHtml($page); ?></b></span> 
    </li>    
  <?php endif; ?>
<?php endforeach; ?>

<!-- Next page link -->
<?php if (isset($this->next)): ?>
    <?php $query['page'] = $this->next;?>
    <li>
        <a href="<?php echo $this->url($this->route, ['action' => $this->action,'id' => $this->id],
                            ['query'=> $query]); ?>
            " aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
        </a>
    </li>  
<?php else: ?>
    <li>
        <span aria-hidden="true">&raquo;</span>      
    </li> 
<?php endif; ?>
</ul>
</nav>
<?php endif; ?>