<div class="col-sm-9">
    <div class="row clearfix">
        <ul>
            <?php foreach ($products as $product) { ?>
                <?php
                $product = $product->getProduct();
                ?>

                <li class="col-lg-3 col-md-3 col-sm-4 col-xs-6 product-image">
                    <div class="card clearfix">
                        <md-layout md-row md-align="right"
                                   class="badge badge-transparent">
                            <?php foreach ($product->getColorsInWord() as $c) { ?>
                                <div style="color: <?php echo $c ?>">
                                    <md-icon>brightness_1</md-icon>
                                    <md-tooltip><?php echo $c ?></md-tooltip>
                                </div>
                            <?php } ?>
                        </md-layout>
                        <img src="<?php echo $this->basePath($product->getImage()) ?>"
                             class="img-responsive product"
                             onclick="location.href = '/product/view/<?php echo $product->getId(); ?>';">
                        <div class="card-meta">
                            <div class="card-title product"
                                 onclick="location.href = '/product/view/<?php echo $product->getId(); ?>';">
                                <?php echo $product->getName(); ?>
                            </div>
                            <div class="clearfix">
                                <div class="card-shop pull-left">
                                    <a href="/category/view/<?php echo $product->getCategory()->getId(); ?>">
                                        <?php echo $product->getCategory()->getName(); ?>
                                    </a>
                                </div>
                                <div class="card-price pull-right">$<?php echo $product->getCurrentPrice(); ?></div>
                            </div>
                        </div>
                    </div>
                </li>

            <?php } ?>
        </ul>
    </div>
    <div class="paginator">
        <?= $this->paginationControl($products,
            'Sliding',
            'product-display/partial/paginator',
            ['route' => 'category',
                'action' => 'view',
                'id' => $category->getId(),
                'params' => $params,
            ]); ?>
    </div>
</div>
