<!-- User Profile -->
<div class="box box-primary">
    <div class="box-body box-profile">
        <img class="profile-user-img img-responsive img-circle"
            src="/img/avatar5.png">
        <h3 class="profile-username text-center">
            <?php echo $user->getName(); ?>
        </h3>
        <p class="text-muted text-center">
            <?php echo $user->getEmail(); ?>
        </p>
    </div>
</div>

<!-- User' Information -->
<div class="box box-primary">
    <div class="box-header with-border">
        <h3 class="box-title">Information</h3>
    </div>
    <div class="box-body">
        <strong>
            <i class="fa fa-map-marker margin-r-5"></i>
            Address
        </strong>
        <p class="text-muted">
            <?php echo $user->getFullAddress(); ?>
        </p>
        <hr>
        <strong>
            <i class="fa fa-phone margin-r-5"></i>
            Phone
        </strong>
        <p class="text-muted">
            <?php echo $user->getPhone(); ?>
        </p>
        <hr>
    </div>
</div>