<div class="row">
    <div class="col-xs-12">
        <div class="box">
            <div class="box-header">
                <h2 class="box-title">List Users</h2>
            </div>
            <div class="box-body">   
                <table id="example" class="table table-striped table-bordered" cellspacing="0" width="100%">
                    <thead>
                        <tr>
                            <th style="width: 15px">#</th>
                            <th>Name</th>
                            <th>Email</th>
                            <th>Phone</th>
                            <th>Address</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach($users as $user): ?>
                            <tr>
                                <td><?php echo ++$i ?></td>
                                <td>
                                    <a href="<?= $this->url('users', ['action' => 'view', 'id' => $user->getId()]) ?>">
                                        <?php echo $user->getName() ?>
                                    </a>
                                </td>
                                <td><?php echo $user->getEmail() ?></td>
                                <td><?php echo $user->getPhone() ?></td>
                                <td><?php echo $user->getFullAddress() ?></td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
