{{ product.description }}

<div class="popup-content" style="min-height: 0px;">
    <div class="content _content">
        <div id="popup-composition"><h5>Composition</h5>
            <ul class="list-composition">
                <li class="section"><p class="title-section">OUTER SHELL</p>
                    <p class="zonasPrenda">100% polyester</p></li>
                <li class="section"><p class="title-section">LINING</p>
                    <p class="zonasPrenda"><u>BODY LINING</u><br>100% polyester</p>
                    <p class="zonasPrenda"><u>SLEEVE LINING</u><br>100% polyester</p>
                    <p class="zonasPrenda"></p></li>
            </ul>
            <h5>Care</h5>
            <ul class="list-cares">
                <li class="clickToolTip"><span class="note">MACHINE WASH UP TO 30ºC/86ºF GENTLE CYCLE</span>
                </li>
                <li class="clickToolTip"><span class="note">DO NOT BLEACH</span>
                </li>
                <li class="clickToolTip"><span class="note">IRON UP TO 110ºC/230ºF</span>
                </li>
                <li class="clickToolTip"><span class="note">DRY CLEAN TETRACHLORETHYLENE</span>
                </li>
                <li class="clickToolTip"><span class="note">DO NOT TUMBLE DRY</span>
                </li>
            </ul>
        </div>
    </div>
</div>
