<div class="footer">
    <div class="footer-inner">
        <div class="footer-content">
            <div class="container">
                <div class="col-sm-5">
                    <div class="clearfix">

                    </div>
                </div>
            </div>
            <div class="basic-info">
                <div class="container">
                        <div class="pull-right">
                            <ul id="basic-info-right">

                                <li>
                                    © 2017 SP14 team.
                                </li>
                                <li>
                                    All Rights Reserved.
                                </li>
                                <li>
                                    <button type="button" class="btn btn-default">Infinishop.</button>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>