<ul id="hlink" class="nav navbar-nav navbar-right hidden-xs hidden-sm">
    <?php if ($user["id"] == 1) { ?>
        <li><a href="/admin">Admin</a></li>
    <?php }; ?>
    <li class="cart_li text-center profile_user">
        <button class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true"
                aria-expanded="false" style="display:block;">
            <?php echo $user["name"] ?>
            <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" style="display:none" />
    </li>
</ul>

<!--Dropdown user menu-->
<ul class="dropdown-menu profile_dd" style="min-width:250px !important; padding: 10px;">

    <li><a href="/user/view" style="padding:5px;border-left:none;">View profile</a></li>
    <li role="separator" class="divider"></li>
    <!--                        <li><a href="#" style="padding:5px;border-left:none;"><span-->
    <!--                                        class="glyphicon glyphicon-envelope"></span>&nbsp; Conversations</a></li>-->
    <li role="separator" class="divider"></li>
    <li><a href="/logout" style="padding:5px;border-left:none;">Sign out</a></li>
</ul>
</li>
</ul>

<!--Menu for mobile-->
<ul id="hlink" class="nav navbar-nav navbar-right hidden-lg hidden-md">
    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
           aria-haspopup="true" aria-expanded="false">
            <?php echo $user["name"] ?>
        </a>
        <ul class="dropdown-menu">
            <li><a href="/user/view">View Profile</a></li>
            <li><a href="/logout">Sign out</a></li>

        </ul>
    </li>
</ul>